
library(Rprebas)
library(Rpreles)
siteInfo <- read.csv("Rprebas_examples-master/inputs/siteInfo.csv",header = T)
thinning <- read.csv("Rprebas_examples-master/inputs/thinning.csv",header = T)
initVar <- read.csv("Rprebas_examples-master/inputs/initVar.csv",header = T, row.names = 1)
weather <- read.csv("Rprebas_examples-master/inputs/weather.csv",header = T)
PAR = c(weather$PAR,weather$PAR,weather$PAR)
TAir = c(weather$TAir,weather$TAir,weather$TAir)
Precip = c(weather$Precip,weather$Precip,weather$Precip)
VPD = c(weather$VPD,weather$VPD,weather$VPD)
CO2 = c(weather$CO2,weather$CO2,weather$CO2)
DOY = c(weather$DOY,weather$DOY,weather$DOY)
PREBASout <- prebas(nYears = 100, PAR=PAR,TAir=TAir,VPD=VPD,Precip=Precip,CO2=CO2)
sink("Output/var1.csv")
print(PREBASout$output[ ,1,1,1])
sink()
sink("Output/var2.csv")
print(PREBASout$output[ ,2,1,1])
sink()
sink("Output/var3.csv")
print(PREBASout$output[ ,3,1,1])
sink()
sink("Output/var4.csv")
print(PREBASout$output[ ,4,1,1])
sink()
sink("Output/var5.csv")
print(PREBASout$output[ ,5,1,1])
sink()
sink("Output/var6.csv")
print(PREBASout$output[ ,6,1,1])
sink()
sink("Output/var7.csv")
print(PREBASout$output[ ,7,1,1])
sink()
sink("Output/var8.csv")
print(PREBASout$output[ ,8,1,1])
sink()
sink("Output/var9.csv")
print(PREBASout$output[ ,9,1,1])
sink()
sink("Output/var10.csv")
print(PREBASout$output[ ,10,1,1])
sink()
sink("Output/var11.csv")
print(PREBASout$output[ ,11,1,1])
sink()
sink("Output/var12.csv")
print(PREBASout$output[ ,12,1,1])
sink()
sink("Output/var13.csv")
print(PREBASout$output[ ,13,1,1])
sink()
sink("Output/var14.csv")
print(PREBASout$output[ ,14,1,1])
sink()
sink("Output/var15.csv")
print(PREBASout$output[ ,15,1,1])
sink()
sink("Output/var16.csv")
print(PREBASout$output[ ,16,1,1])
sink()
sink("Output/var17.csv")
print(PREBASout$output[ ,17,1,1])
sink()
sink("Output/var18.csv")
print(PREBASout$output[ ,18,1,1])
sink()
sink("Output/var19.csv")
print(PREBASout$output[ ,19,1,1])
sink()
sink("Output/var20.csv")
print(PREBASout$output[ ,20,1,1])
sink()
sink("Output/var21.csv")
print(PREBASout$output[ ,21,1,1])
sink()
sink("Output/var22.csv")
print(PREBASout$output[ ,22,1,1])
sink()
sink("Output/var23.csv")
print(PREBASout$output[ ,23,1,1])
sink()
sink("Output/var24.csv")
print(PREBASout$output[ ,24,1,1])
sink()
sink("Output/var25.csv")
print(PREBASout$output[ ,25,1,1])
sink()
sink("Output/var26.csv")
print(PREBASout$output[ ,26,1,1])
sink()
sink("Output/var27.csv")
print(PREBASout$output[ ,27,1,1])
sink()
sink("Output/var28.csv")
print(PREBASout$output[ ,28,1,1])
sink()
sink("Output/var29.csv")
print(PREBASout$output[ ,29,1,1])
sink()
sink("Output/var30.csv")
print(PREBASout$output[ ,30,1,1])
sink()
sink("Output/var31.csv")
print(PREBASout$output[ ,31,1,1])
sink()
sink("Output/var32.csv")
print(PREBASout$output[ ,32,1,1])
sink()
sink("Output/var33.csv")
print(PREBASout$output[ ,33,1,1])
sink()
sink("Output/var34.csv")
print(PREBASout$output[ ,34,1,1])
sink()
sink("Output/var35.csv")
print(PREBASout$output[ ,35,1,1])
sink()
sink("Output/var36.csv")
print(PREBASout$output[ ,36,1,1])
sink()
sink("Output/var37.csv")
print(PREBASout$output[ ,37,1,1])
sink()
sink("Output/var38.csv")
print(PREBASout$output[ ,38,1,1])
sink()
sink("Output/var39.csv")
print(PREBASout$output[ ,39,1,1])
sink()
sink("Output/var40.csv")
print(PREBASout$output[ ,40,1,1])
sink()
sink("Output/var41.csv")
print(PREBASout$output[ ,41,1,1])
sink()
sink("Output/var42.csv")
print(PREBASout$output[ ,42,1,1])
sink()
sink("Output/var43.csv")
print(PREBASout$output[ ,43,1,1])
sink()
sink("Output/var44.csv")
print(PREBASout$output[ ,44,1,1])
sink()
sink("Output/var45.csv")
print(PREBASout$output[ ,45,1,1])
sink()
sink("Output/var46.csv")
print(PREBASout$output[ ,46,1,1])
sink()
